LilycoveCity_DepartmentStore_3F_MapScripts:: @ 8159F90
	.byte 0

LilycoveCity_DepartmentStore_3F_EventScript_159FE2:: @ 8159FE2
	msgbox LilycoveCity_DepartmentStore_3F_Text_18C24B, MSGBOX_NPC
	end

LilycoveCity_DepartmentStore_3F_EventScript_159FEB:: @ 8159FEB
	msgbox LilycoveCity_DepartmentStore_3F_Text_18C2B5, MSGBOX_NPC
	end

LilycoveCity_DepartmentStore_3F_EventScript_159FF4:: @ 8159FF4
	msgbox LilycoveCity_DepartmentStore_3F_Text_18C32E, MSGBOX_NPC
	end
