LilycoveCity_DepartmentStore_4F_MapScripts:: @ 8159FFD
	.byte 0

LilycoveCity_DepartmentStore_4F_EventScript_159FFE:: @ 8159FFE
	msgbox LilycoveCity_DepartmentStore_4F_Text_18C39C, MSGBOX_NPC
	end

LilycoveCity_DepartmentStore_4F_EventScript_15A007:: @ 815A007
	msgbox LilycoveCity_DepartmentStore_4F_Text_18C41B, MSGBOX_NPC
	end

LilycoveCity_DepartmentStore_4F_EventScript_15A010:: @ 815A010
	msgbox LilycoveCity_DepartmentStore_4F_Text_18C481, MSGBOX_NPC
	end
