LilycoveCity_DepartmentStore_2F_MapScripts:: @ 8159F0E
	.byte 0

LilycoveCity_DepartmentStore_2F_EventScript_159F0F:: @ 8159F0F
	msgbox LilycoveCity_DepartmentStore_2F_Text_18C162, MSGBOX_NPC
	end

LilycoveCity_DepartmentStore_2F_EventScript_159F18:: @ 8159F18
	msgbox LilycoveCity_DepartmentStore_2F_Text_18C195, MSGBOX_NPC
	end

LilycoveCity_DepartmentStore_2F_EventScript_159F21:: @ 8159F21
	msgbox LilycoveCity_DepartmentStore_2F_Text_18C1D9, MSGBOX_NPC
	end
